travis:
  secure:
    BINSTAR_TOKEN: SpVspaHap4u9Ja3YYGSO2is5ufU+v5BAdh3Kqs94WWvRZwOvdDdA08xUqSVSJS26cE1AuloXOqsecSz1tuvZjC5l7yC+8vGOWkE/NKfX/UyHKU3r5hYh/7JyrPGPNyLxxTd+ml2KpCKECwrPRTwZoqlQs2dvqKjkJJsR6W8TOThQBe38iy+eKtgpmw5HFqHbH7AloYciX2U8RePi+N/WaE54/iRvdCajq+z/ymeiU9IFBVjS45DrsKFnCb6pso7EVJXL7vrLF2vYEoXHBNRf7jYKMxh79+Ehfs2yoIVlBm3wdgFssox+XAAvdXokBbPXkm5DLLEzXdSMPK3iRY/ctEdwGG400kctcBeqGwFVAgWcJhMpSTam5m64yV0+mzJAOD8NtHnnHfS5i0Md3fTpFedgjidD8eOlfX6OZrqc1HNKv71rSp7P4jIH7rwkB7dgezpRvSIGv4gp26mKeXnHd9imECmDVLuI6xa2szw76DNHzNVM8Bq2i1njgOXqmwEjIiEP36G3jZ+2AuNbWKpe3fR49M7+5LlJ2DW3mgTews1i5FnKQ9By07827BwWWo0PVu+qA8jjhAdVJPp/3ezwzAg7pLPgFiILLAxqmi07aZtONnWR9Q/dcb6OXJFmV5AyhdhFyjhUAa9A+MuYeh5WnZkVbYkZpLvjH3dBTmLQLQ8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
