travis:
  secure:
    BINSTAR_TOKEN: Bpt5I7Gozcbd1NZfYla/vF+thT2rF9jVSX6WUbhKRF35BUfkqu5MiBiDCdYrV2bh9zUf6gz+lZyngsAjjxfm9w3swZZUPjU/To8aqMqTeicaO66mdNptWs7r7Mii1tW6/uwB/QtxezqEkKQtwXa5MlT98gVVgBMkGgxm3Yo5og//bzeTSm6siGBOiQahZ/lVw9l1YzOMqFva8h6KS10OOHH6f7V+XCm9mEFoLDL6d9w29v0hrqcCOZlQeW/8AyCclukNxM2x7k4GjxFrxLmPoGF/cf2fumHrc6cTOvugodJkjtoFF5Qq2r5OeJ18UT3TCwr54lwfQWoQNplfxR7s6B3qWznqdUs9f4MbRYYwzFt2ZzHqItbXploiJF3hx4Rld2HzpVbdsUBMa4+IzOrbYkYTI9AX/9R4T978JF4ydobCMsMDkBV7gH42sDoUekro4BG6uyBB5RF7uEMBsIsLLZicaC/9SLuivCOQyJJUgM0ztwIErZCONi/DW5L/4maRjCKPoPCPSZlVoFj9tVEITtvNNRZWYzROUAD9whx+cyjQAFNJL9wk/nrf/LqEY/BLk9suheQXnfrpcfLqBXO1bsZ98eBui/IwjpLGcM/ekIeefbEdb1u3VWuwhhMEzC/yCO9a6kJDrWVaFiNdZrW7izM6sxjddGMuQ8z3jOl4orE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
