travis:
  secure:
    BINSTAR_TOKEN: eSp40s4VPydPaqxDLMTsWS1zWOiOGsDfxLKQ1oeAaemgVlylCS89OGKeHN+bJQof5SKObBZn2Grz5FU1rru/IlT9SKtSDT/ZBldQ/3RpkHwkr+wKEJPWEPCVN733XqQMJdKQxmAv5PXehk33zBwzymdBhhdYG2XEuOdthScJKaUI99BM/yUllU5pVpIFlJtJFUpR2vAhS0PI3Y4Zy5PLldpC7a4H5/PqgVegiGP9AhWZv58ACQfRcvxIHVJt5DmmR3ZDNXMCX+1qDRoZYPFWEcdRFOgnYpgjl4UiurIYDAHyukg0syuSPPUsqXPNcX99FMSPTZ7vuW697rAeV4OBzlwMBow0pXTS+FrBNk7ycZlcEmsBwjpROoZNQvuH45AucKlJAQOhwc1G+tNKOy2GUpzumKOy4u7ulQU6mqtWa2Xk89I6XpAN6oJcjJXfUca5DI/+sI1aT6mT69hVOEDLEJDT1RhohnF8I3oIOMqnMSh7FvLoRTf3lpMXLKLcEfrZ0nxc4JobRn1qcJ0u8NeDv7OVtE3FSNw2AiLWCSXtw8DHeZbQXkO7kpZz9G2pSB12+obVH4lNnzyX3VxcZ2/HYFxOzKYkaoNZyODvMrMNVoYVqmO0Mlk4kPFUu0mGHhSawlsAiu9FgdPQbMlIoxnWMELCwPYnVnoVFQiwwiSE3L4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
